module.exports = {
    changenodezy:{
        canusemoney:'可用余额',
        total:'全部',
        inputamount:'输入数量',
        changenode:'更&nbsp;换&nbsp;节&nbsp;点&nbsp;质&nbsp;押',
        note1:'更换节点说明：',
        note2:'将您的NOVA选择一个新的节点进行质押。更换时间为21天，21天后更换至新的节点并开始产生收益。',
        numbernotzero:'输入数量不能为0',
        nogetaddress:'未取到列表节点地址，请返回重试',
        noauthtoken:'未授权成功',
        changenodealert:'更换节点质押成功'
    },
    index: {
        total: '总资产',
        balance: '可用余额',
        yesterdayIncome: '昨日收益',
        totalIncome: '累计收益',
        pendingAmount: '赎回中',
        choosenode: '选择节点质押',
        usenote: '使用说明',
        problem: '常见问题',
        mynode: '我的质押节点',
        alertauth:'未授权成功,请退出重新授权'
    },
    moneyrecord: {
        totalmoney:'总金额',
        shoyyi: '收益',
        jine: '累计收益',
        mypledgeAmount:'我的质押数量'
    },
    mynodedetail: {
        zyje: '节点质押数量',
        yeargetmoney: '预计年化收益',
        nodespeak: '节点宣言',
        myziyaje:'我的质押数量',
        moneyrecord: '收益记录',
        shuhui: '赎回',
        zhiya: '质押',
        nearamount:'最近交易',
        acounting:'进行中的交易',
        changenodezy: '更换节点质押',
        changenodezyfailed:'更换失败',
        changenodezysuccess:'更换成功',
        shuhuiing: '普通赎回中',
        onceshuhuiing:'立即赎回中',
        ordinaryshuhui: '普通赎回',
        onceshuhui:'立即赎回',
        changeing: '更换中',
        packageing: '交易正在打包',
        cancelshuhui: '取消赎回',
        cancelchange: '取消更换',
        zhiyaing:'质押中',
        zhiyafailed: '质押失败',
        zhiyacancel: '质押撤销',
        waiting: '转账等待',
        shuihuisuccess: '赎回成功',
        shuihuifailed: '赎回失败',
        shuhuicancel: '赎回撤销',     
        zhiyasuccess: '质押成功',
         zhuanchu:'转出',
         zhuanchuing:'转出中',
         zhuanchusuccess:'转出成功',
         zhuanchufailed:'转出失败',
         zhuanchucancel:'转出撤销',
         dadaloading:'数据加载中',
         nogetservicenode: '未取到服务器节点',
         canceled:'已取消',
         cancelfailed:'取消失败',
         changenodeshuhui:'赎回',
         changenodeshuhuifailed:'赎回失败',
         changenodeshuhuisuccess:'赎回成功'
    },
    nodeswiper: {
        effectnode: '提案节点',
        invalidnode: '普通节点'
    },
    problem: {
        problem: '常见问题',
        q1: '什么是节点负责人',
        q1note: '在Nova“质变”计划中，质押量≥ 300 万即可申请成为节点负责人，并创建属于自己的节点，NOVA持有者可以将NOVA质押进任意节点并获得节点收益，而节点负责人可以拿到额外比例的奖励，同时节点负责人也可以是节点参与者。成为提案节点负责人后将获得Nova生态提案权、投票权。',
        q2: '什么是节点参与者？',
        q2note: '在Nova基金会推出的Nova“质押”计划中，任何持有NOVA的用户都可以自主选择将NOVA质押进任意节点，通过质押来获得节点收益。',
        q3: '为什么要质押NOVA？',
        q3note: 'Nova基金会将拿出投资孵化的项目收入回购NOVA代币存入节点作永久锁仓处理，将NOVA代币进行通缩。随着节点产生，质押的NOVA成线性增长过程中二级市场流通的代币同比例减少，NOVA代币的价格也会相应上升。随着节点参与者的增加最终将会形成良性质押生态，所有持币者都将获得丰厚的回报。',
        q4: '加入NOVA质押计划有哪些收益？',
        q4note: 'Nova基金会会拿出1亿代币作为质押模型的奖励给节点参与者。基金会将NOVA通行通缩，币价相应会提升。',
        q5: '质押何时生效，质押多久后开始获得收益？',
        q5note: 'NOVA持有者将NOVA质押进节点后即刻生效并成为节点参与者，质押收益将次日 00：00（新加坡UTC+8）结算并发放至账户中。',
        q6: '质押后能否赎回？',
        q6note: '质押后可以随时赎回您质押的NOVA，赎回方式分为”普通赎回”和“立即赎回”。 普通赎回：赎回到账时间为T+21天，赎回的NOVA将转入到您的钱包地址，赎回期间的质押不产生收益，且将扣除质押总额1%的NOVA作为手续费并进行永久销毁；立即赎回：赎回质押可立即到达您的钱包地址，且将扣除扣除质押总额10%的NOVA作为手续费并进行永久销毁',
        q7: '节点负责人是否会向节点参与者收取「管理费」？',
        q7note: '节点负责人的额外节点建立奖励由基金会出资。',
        q8: '把NOVA质押进节点是否有风险？',
        q8note: '被质押的NOVA会作锁仓处理，并可以随时赎回。如果节点参与者行为不端，作出不利于Nova生态发展的动作，将会有部分NOVA被罚没，相应节点负责人也会收到一定惩罚，所以节点负责人在接受节点参与者质押前应该对参与者进行严格的资质评估。',
        q9:"点了普通赎回后不想赎回了怎么办？",
        q9note:"您可以在普通赎回到账之前的任意时间节点点击“取消赎回”，系统将即时取消您的赎回操作。",
        q10:"如何更换节点质押？",
        q10note:"将质押在A节点的NOVA点击“更换节点质押”再选择质押进B节点即可，更换节点质押到账时间为T+21天，在21天中不产生收益，直至更换到B节点后开始产生收益，更换节点质押过程中可以选择“取消更换”，且更换节点质押无手续费。",

    },
    rule: {
        txt1: 'Nova基金会的愿景是为去中心化金融搭建一个长期并可持续发展的生态系统，Nova激励协议项目代币NOVA将起到关键性作用，故Nova基金会决定推出NOVA【质变】计划(NOVA Staking Economy)。',
        txt2: '规则如下:',
        txt3: '参与条件：任何持有 NOVA 的用户都可以选择任意节点质押任意数量的NOVA，成为 NOVA 节点参与者。',
        txt4: '质押量要求：无限制。',
        txt5: '申请节点：任何节点参与者都可以申请建立自己的节点，当节点质押数≥ 300万，节点正式生效，申请人自动升级为节点负责人。',
        txt6: "节点规则:节点分提案节点和普通节点。 普通节点：质押量≥ 300 万即可自动升级为普通节点，获得收益。 提案节点：初始提案节点为 1，总质押数量（所有节点质押数量总和）每增加 3000 万系统自动增加 1 个提案节点，成为提案节点可参与项目的规划、发展、有权利进行提案和投票。",
        txt7: '节点收益计算：用户可随时赎回已质押的 NOVA，质押收益将于次日开始计算。',
        txt8: '收益将于每日 00：00（新加坡UTC+8）结算并发放至账户中。年化收益计算：',
        txt9: '规则如下:',
        txt10: 'B代表年化收益',
        txt11: 'N代表质押总额',
        txt12: '节点参与者将按质押比例获得节点每日收益。'
    },
    shuhui: {
        zhiyaed: '已质押',
        amountLimit:'输入不能大于您当前的Nova',
        total: '全部',
        placeholder: '输入数量',
        atonceshuhui: '立即赎回',
        normalshuhui: '普通赎回',
        shuhui: '赎&nbsp;&nbsp;&nbsp;&nbsp;回',
        note: '赎回说明：',
        note1: '普通赎回：赎回到账时间为T＋21天，赎回的NOVA将转入到您的钱包地址，同时赎回期间的质押不产生收益，并将扣除1%的手续费销毁。立即赎回：赎回质押可立即到达您的钱包地址，但同时扣除总额10%的手续费并永久销毁。',
        numbernotzero:'输入数量不能为0',
        nogetaddress:'未取到列表节点地址，请返回重试',
        noauthtoken:'未授权成功',
        changenodealert:'赎回成功'
    },
    zhiya: {
        canusemoney: '可用余额',
        amountLimit:'输入不能大于您当前的Nova',
        total: '全部',
        placeholder: '输入数量',
        gasprice:'预计交易费：',
        zhiya: '质&nbsp;&nbsp;&nbsp;&nbsp;押',
        note1: '质押说明:',
        note2: '将您的NOVA选择一个节点进行质押。在质押期间，可以享受质押带来的收益，也可以进行赎回，立即赎回需要扣取10%的手续费，普通赎回是需要扣除1%的手续费用,普通赎回质押需要等待T+21天后转入钱包。',
        numbernotzero:'输入数量不能为0',
        nogetaddress:'未取到列表节点地址，请返回重试',
        noauthtoken:'未授权成功',
        zhiyanodealert:'质押成功'
    },
    components: {
        alert: {
            title: '请授权给nova使用钱包链接',
            cancel: '取消',
            certain: '确认',
            slowtext:'您将要进行普通赎回，赎回的NOVA将在T+21天后转入您的钱包内，将扣除赎回总额的1%作为手续费进行销毁。',
            atoncetext:'您确定要立即赎回吗？立即赎回将扣除赎回总额的10%作为手续费，手续费将永久销毁。',
            changenodepledgetext1:'您确定将',
            changenodepledgetext2:'NOVA，转至',
            changenodepledgetext3:'节点吗，更换节点需T+21天，无手续费'
        },
        effectnode: {
            nodata: '暂无数据~',
            zhiyatotalmoney: '质押总额',
            yujiyearmoney: '预计年化收益',
            zhiya: '我的质押',
            shouyi: '收益',
            moneyday: '预计收益(天)',
            cannotchoosesamenode:'不能选择和旧节点相同的地址质押'
        },
        homelistnode: {
            valiednode: '普通节点',
            effectnode: '提案节点',
            zhiyatotalmoney: '质押总额',
            yujiyearmoney: '预计年化收益',
            zhiya: '我的质押',
            shouyi: '收益',
            moneyday: '预计收益(天)',
        },
        invalidnode: {
            nodata: '暂无数据~',
            nomoney: '余额不足',
            zhiyatotalmoney: '质押总额',
            yujiyearmoney: '预计年化收益',
            zhiya: '我的质押',
            shouyi: '收益',
            moneyday: '预计收益(天)',
            cannotchoosesamenode:'不能选择和旧节点相同的地址质押'
        }
    },
    language: {
        name: 'English'
    },
}